FORMAT: 1A

# ggvb API

# Group Transactions

## Transactions [/api/transactions]
### List all Transactions [GET]
+ Response 200 (application/json)

        [
            {
                "id": 1,
                "description": "Philz Coffee",
                "amount": 3.5,
                "date": "2014-11-15"
            },
            {
                "id": 2,
                "description": "Toy for Violet",
                "amount": 6.78
                "date": "2014-11-16"
            }
        ]
